env:
- COVERAGE: true
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
install:
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
notifications:
  email: false
  slack:
    secure: ddF1vp9zeEZNYZnz12NEsWxUrfkqVHyx5yY3WiwWcAEdxpS3Q6q+gZfB8dAm+LNIgzqFcrUdY1wcX4EPSD7ID2bCrtV1qdEDffn1PLGsUypf67xM/cC+iPBzmoKsvLb4lquxWYEubzLmTMNjvehrKXmyb+1RXr/TbYrrKsgAzfim8S2K7nPUMlmkSIrBVdeYKTTcJqdbhrXCuMgrvPC2oSYKsbreAK4DJzmzYFO1XpFMj9O855TMBVUIFKGnekmZPNtqh1N+jShrz8rqa1I8ZgayCqMGvk6bL7TQLsnk5D6PYO7aUqKLqbBRlbkJft7v+zI1wuu3Rw+DZYGq6TtRLlSh/AI0GnNXMlA/dpWFPb52o1O9CbsBzRXvk2dwRWpKZsYwR7PhLIoMCvfD54Oq5Fn8yGPDnXXe3DXrXQ9Emx5K5Fz9p0vac1pde91Mo7y5H4b6PmE9JU3kgIOUZzTp+xReU8KrP/efdp5Wr6KCzLhYqQnEeHq7Y2BwNK/mov/vI857cua9KAQgruwLKSuvFz7IsAh/6wXI1r40IMlVB7DNs+V6YeMMXE3sSlP0I2CMzMeiI8ZrCLn0jkciMAjIX7+XZ7CJUaOXcuuMsmsQpodmTn3pn+VSt5a7AnGZ/id+1tbW1slsSKluaODDib7hFmZYloiYnc9U7sbae5TNzm0=
